[package]
name = "volumate"
version = "0.1.0"
edition = "2021"

[dependencies]
winmix = "0.1.3"
actix-web = "4"
actix-cors = "0.7"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
local-ip-address = "0.5"
colored = "2"
